language: python
dist: xenial
python:
- 3.6
- 3.7
install:
- pip install --upgrade pip
- pip install -r dev-requirements.txt
- pip install -r requirements.txt
script: make lint && make test
after_success:
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
deploy:
- provider: script
  skip_cleanup: true
  script: make deploy ENV=$ENVIRONMENT_NAME
  on:
    branch: development
env:
  global:
  - secure: oD4eCnO5qvIg76d2FLnIqqGOq4n84RX643ohJxnCAF0nBFWk3HaRgJUR395tL9svtDlhJVZOa3nBh49tWPFDWZ0Ous7IwjGVv+A/zlRrc9RkRbVEuIv/29GuaGJnbQ8PrDF7ifexWyKsBjcSya70rAd22RVK/ol8HK0ubmRb1vdRVSILblWHM6IEMIoodnhReVixR80f+9vuGaqCjQINzTGSLGLiGScXaYhaad1k6KvIXIk3NgMBhqsjIXQzn7xpRaaapi1C8RQsYymvHm2ZuWTqkqrXpGq1UDt5nklXuHgUhgziy+hbYVv6Epb2gqvwuHCr3SYWtKKLGWJ/CgIB0Ozt5M6qYLdsQ9Y4uopgwePtARxVLnXsPrzSqFW0NW47vhUXQJuUGl2hbbyEe1mpg6AuykhDfNYPITFmR6eMUzvmERzyN/zilOExwR+dLKYvWjbHuTElkEeMwe3ONVGWyAcvoSl7yyQPSoeMHx7xPeU5pCEsDAibvMHxG4rPW+BY04DzZvy8UO215wSSGyduA7ccspcQtFTepFjjh3z4AYshEYEWSn8bkzA1fvCdU+GKK8OdHqWAlznJEq1WS5y9GBKd6cjQBY14NrGFfsHxk1NFQyydA26FWR4IKEc/nyWcdruzSEXsZVp9kzzG4EaKeYhQJxUVJIy4A9XcY6dgFro=
