# Uncomment the below/add additional env variables to add them to the lambda
runtime: python3.7

# === ENVIRONMENT_VARIABLES ===
environment_variables:
    LOG_LEVEL: debug
    UPDATE_PERIOD: '1200'
    
    KINESIS_INGEST_STREAM: sfr-db-ingest-development

    ACTIVE_READERS: IAReader

    IA_ACCESS_KEY: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQH7XOL/2vtRgY8Y57H1MgnzAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFvl6v1fX/jv7FXj/AgEQgCvUNHeEC7CC/XtEAPUbT6u2nXJzrItDsrvdoVwchWrhcRGMTk75L5372qX9
    IA_SECRET_KEY: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQHsOhPKQbKOD9lUuCeYR2RpAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwRFCf9cKYskRF07CAgEQgCvHNYPAog87aqAW46jhOo4yYHIGkVcoqKnjyVmiSXeGH0WidEEFZhkp7zuV
    IA_COLLECTIONS: guggenheimmuseum
    