# Uncomment the below/add additional env variables to add them to the lambda
runtime: python3.7

# === ENVIRONMENT_VARIABLES ===
environment_variables:
    LOG_LEVEL: debug
    UPDATE_PERIOD: '1200'
    
    KINESIS_INGEST_STREAM: sfr-db-ingest-development

    ACTIVE_READERS: IAReader

    IA_ACCESS_KEY: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQH7XOL/2vtRgY8Y57H1MgnzAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFvl6v1fX/jv7FXj/AgEQgCvUNHeEC7CC/XtEAPUbT6u2nXJzrItDsrvdoVwchWrhcRGMTk75L5372qX9
    IA_SECRET_KEY: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQHI5/PaiGkThNhvYXsuwCN1AAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIcudFskHVMcr+dK/AgEQgCsdbxdF0W4Zcqp4UKPfoTiamgnVS288ZanZoQj25LzoAOsXiomjFRV+eiI
    IA_COLLECTIONS: guggenheimmuseum
    