# Uncomment the below/add additional env variables to add them to the lambda
runtime: python3.7

# === ENVIRONMENT_VARIABLES ===
environment_variables:
    LOG_LEVEL: debug
    UPDATE_PERIOD: '20000'
    
    KINESIS_INGEST_STREAM: sfr-ingest-development

    CONTENT_CAFE_USER: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQE1hKUrkQ7dKsGgxuMxGzVKAAAAZzBlBgkqhkiG9w0BBwagWDBWAgEAMFEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFguaM5tzTaKC/1eyAgEQgCRhHumeTOfFDS8DFC7H9FvuYW894eKjvFZSegixk6qn5J2xAh0=
    CONTENT_CAFE_PSWD: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQHkmarCq22R3b1gnlZDGS3TAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfxPigxIBjYON6KxZAgEQgCJv/nMFZEeYXGzWvTGpsrKPAo6gKJZZhxofMlEDMf+z4VXM

    GOOGLE_BOOKS_KEY: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQHm38xla41Z0FXID/r2f9GLAAAAhjCBgwYJKoZIhvcNAQcGoHYwdAIBADBvBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJGUefNT8tY4sFOfLwIBEIBCFYgFPFGkMmyWRiLjW1/4jU3L+cizTOHKQ1f1p/Eyd8oZuGQv+dkX1SwimubxsAbFacQMYqur1kpP60XRt4UuEHJy

    DB_HOST: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQFS0Isq8hTqldHZQzUgP2ESAAAAoTCBngYJKoZIhvcNAQcGoIGQMIGNAgEAMIGHBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHzShifJFRgWwJNUxQIBEIBaw6esXHPhPo72yKfXMhjQBiRRgzMwxDENRL5/7/qbiBCS6SYeeCEzOZBLwmyrQgCsZzRu2AMWThnEAv20EYWbQ2AWN7cFXQFNQknXb9lHihFfm0rXsjES7qMe
    DB_PORT: '5432'
    DB_NAME: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQH7AvfDTw5Pu0IgG0/KnOf9AAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzNrTcjRPWZYYGVu7AgEQgCKq5qEs/w008VON8/IFLe5vtRfplBxHMzNjkmCM1KUyQUP+
    DB_USER: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQEkoQNYODSk+m8cJJethF9fAAAAYTBfBgkqhkiG9w0BBwagUjBQAgEAMEsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRn26MsM9MH+2cXAyAgEQgB7gWCou8rWbTzfnj2dpcXupJEiP4FcYNo9x0b5Au44=
    DB_PSWD: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQF9q6qZdlshh6jj9SCwRnrxAAAAaTBnBgkqhkiG9w0BBwagWjBYAgEAMFMGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3VcD1csTm05LRnTxAgEQgCaaffMztl8n0z5ic66yft0nGxzX8141R/Y987kqXEeQYemN4DJ2zg==
    DB_OL_NAME: AQICAHg44Tmwi+nLR/0IeFODcEqu2nSlqdDZMsDWalEb1O+LSQHsOlQ0hxtJLG0V9GiIF8NpAAAAYzBhBgkqhkiG9w0BBwagVDBSAgEAME0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMH1IBW0vZ/5xQwQy9AgEQgCASIqJHo7BT/2Bygo8TzkqYpoXkuIqFIUVqtnNaUvG6lA==